1. Create a function that transposes a 2D matrix.

__Ans:-__

In [1]:
from numpy import transpose

def transpose_matrix(mat):
    return transpose(mat)
print(transpose_matrix([
  [5, 5],
  [6, 7],
  [9, 1]
]) 
)
print()
print(transpose_matrix([
  [1, 1, 1],
  [2, 2, 2],
  [3, 3, 3]
])
)

[[5 6 9]
 [5 7 1]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]


***

2. Create a function that determines whether a string is a valid hex code.

    A hex code must begin with a pound key # and is exactly 6 characters in length. Each character must be a digit from 0-9 or an alphabetic character from A-F. All alphabetic characters may be uppercase or lowercase.

__Ans:-__

In [2]:
import re
def is_valid_hex_code(hex_code):
    if len(hex_code) != 7 or hex_code[0] != '#':
        return False
    result = re.search(r'[^a-f0-9]+', hex_code[1:], re.IGNORECASE)
    return True if not result else False

print(is_valid_hex_code("#CD5C5C"))
print(is_valid_hex_code("#EAECEE"))
print(is_valid_hex_code("#eaecee"))
print(is_valid_hex_code("#CD5C58C"))
print(is_valid_hex_code("#CD5C5Z"))
print(is_valid_hex_code("#CD5C&C"))
print(is_valid_hex_code("CD5C5C") )

True
True
True
False
False
False
False


***

3. Given a list of math equations (given as strings), return the percentage of correct answers as a string. Round to the nearest whole number.

__Ans:-__

In [3]:
def mark_maths(lis):
    return str(round(sum(list(map(lambda x : eval(x.split('=')[0]) == int(x.split('=')[1]), lis)))/len(lis) * 100)) + '%'
    
print(mark_maths(["2+2=4", "3+2=5", "10-3=3", "5+5=10"]) )
print(mark_maths(["1-2=-2"]))
print(mark_maths(["2+3=5", "4+4=9", "3-1=2"]))

75%
0%
67%


***

4. There are two players, Alice and Bob, each with a 3-by-3 grid. A referee tells Alice to fill out one particular row in the grid (say the second row) by putting either a 1 or a 0 in each box, such that the sum of the numbers in that row is odd. The referee tells Bob to fill out one column in the grid (say the first column) by putting either a 1 or a 0 in each box, such that the sum of the numbers in that column is even.

    Alice and Bob win the game if Alice’s numbers give an odd sum, Bob’s give an even sum, and (most important) they’ve each written down the same number in the one square where their row and column intersect.

__Ans:-__

In [4]:
def magic_square_game(alice, bob):
    return True if sum(list(map(int, alice[1]))) % 2 and not sum(list(map(int, bob[1]))) % 2 and \
                    alice[1][bob[0] - 1] == bob[1][alice[0] - 1] else False

print(magic_square_game([2, "100"], [1, "101"]))
print(magic_square_game([2, "001"], [1, "101"]))
print(magic_square_game([3, "111"], [2, "011"]))
print(magic_square_game([1, "010"], [3, "101"]))
print(magic_square_game([1, "111"], [3, "101"]))

False
True
True
False
True


***

5. From point A, an object is moving towards point B at constant velocity va (in km/hr). From point B, another object is moving towards point A at constant velocity vb (in km/hr). Knowing this and the distance between point A and B (in km), write a function that returns how much time passes until both objects meet.

    Format the output like this:

    "2h 23min 34s"

__Ans:-__

In [5]:
import time
def lets_meet(dist, A_speed, B_speed):
    return time.strftime("%Hh %Mmin %Ss", time.gmtime(dist/((A_speed + B_speed)) * 3600))

print(lets_meet(100, 10, 30))
print(lets_meet(280, 70, 80))
print(lets_meet(90, 75, 65))

02h 30min 00s
01h 52min 00s
00h 38min 34s
